[build]
  command = "NODE_OPTIONS='--max-old-space-size=4096' npm install --legacy-peer-deps && npm run build"
  publish = "build"


[context.production.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--max-old-space-size=4096"
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
